### ISSUE TITLE
Portability on ARM systems

### ISSUE THREAD

**Issue by Hiradur** [lunixbochs/tinygles#8]
I tried to build TinyGLES on a Raspberry Pi 2 with Raspbian armhf and it failed because the libs it links against were compiled with -mfloat-abi=hardfp.

Removing `-mfloat-abi=softfp` in this passage in CMakeLists.txt fixes it:

``` cmake
if(CMAKE_SYSTEM_PROCESSOR MATCHES "^arm")
    add_definitions(-fsingle-precision-constant -mfloat-abi=softfp -mfpu=neon -march=armv7-a -mcpu=cortex-a8 -mtune=cortex-a8)
endif()
```

But I think this whole if-clause is a bad idea because it enforces armv7 builds on all ARM architectures.

**Comment by lunixbochs** [comment]
You're not very likely to get good performance out of this on armv6, so I don't feel too bad about it. It's heavily neon-optimized, so armv7+ is my target.

def938ad67940bb39682dbb20000506954934845
